import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Supported languages
enum AppLanguage { english, hindi, marathi }

// Language codes for each supported language
final Map<AppLanguage, String> languageCodes = {
  AppLanguage.english: 'en',
  AppLanguage.hindi: 'hi',
  AppLanguage.marathi: 'mr',
};

// Get the AppLanguage from a language code
AppLanguage getLanguageFromCode(String code) {
  return languageCodes.entries
      .firstWhere((entry) => entry.value == code,
          orElse: () => const MapEntry(AppLanguage.english, 'en'))
      .key;
}

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  // Helper method to keep the code in the widgets concise
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  // Static member to have a simple access to the delegate from the MaterialApp
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Translation maps for each supported language
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Common strings
      'app_name': 'KindMeals',
      'app_slogan': 'Share Food, Share Love',
      'get_started': 'Get Started',
      'continue': 'Continue',
      'inspirational_quote': 'When we give cheerfully and accept gratefully, everyone is blessed.',
      'no_image_available': 'No image available',
      
      // Dashboard screen
      'welcome_to': 'Welcome to',
      'top_volunteers': 'Top Volunteers',
      'top_donors': 'Top Donors',
      'view_full_leaderboard': 'View Full Leaderboard',
      'reviews_feedback': 'Reviews & Feedback',
      'view_all_reviews': 'View All Reviews',
      'support_a_cause': 'Support a Cause',
      'donate_to_kindmeals': 'Donate to KindMeals',
      'donate_subtitle': 'Support our mission to reduce food waste and hunger',
      'donate_now': 'Donate Now',
      'view_all_charities': 'View All Charities',
      'name': 'Name',
      'deliveries': 'Deliveries',
      'meals': 'Meals',
      'no_volunteers_found': 'No volunteers found',
      'no_donors_found': 'No donors found',
      'refresh_data': 'Refresh Data',
      
      // Volunteers Screen
      'volunteers': 'Volunteers',
      'volunteer_leaderboard': 'Volunteer Leaderboard',
      'total_volunteers': 'Total Volunteers',
      'total_deliveries': 'Total Deliveries',
      'avg_deliveries': 'Avg Deliveries',
      'rank': 'Rank',
      'volunteer': 'Volunteer',
      'deliveries_made': 'deliveries made',
      'become_volunteer': 'Become a Volunteer',
      
      // Motivational content
      'feed_smile': 'Feed a Smile Today',
      'meal_brighten': 'One meal can brighten someone\'s whole day',
      'share_table': 'Share Your Table',
      'no_hunger': 'No one should go hungry in our community',
      'food_waste': 'Food Waste to Food Taste',
      'rescue_food': 'Rescue surplus food and feed those in need',
      'donate_what': 'Donate What You Can',
      'every_contribution': 'Every contribution makes a difference',
      'hunger_stat': '1 in 9 People Go Hungry',
      'change_stat': 'Your donation can change this statistic',
      
      // Social Media Footer
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'contact_us': 'Contact Us',
      'all_rights_reserved': '© 2025 KindMeals. All rights reserved.',
      
      // Profile Screen
      'profile': 'Profile',
      'try_again': 'Try Again',
      'edit': 'Edit',
      'logout': 'Log Out',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'error_loading_profile': 'Error loading profile',
      'change_language': 'Change Language',
      'personal_information': 'Personal Information',
      'contact_information': 'Contact Information',
      'organization_information': 'Organization Information',
      'about': 'About',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'contact_number': 'Contact Number',
      'address': 'Address',
      'organization_name': 'Organization Name',
      'organization_id': 'Organization ID',
      'description': 'Description',
      'no_description': 'No description available',
      'profile_image_updated': 'Profile image updated successfully',
      'failed_upload_image': 'Failed to upload profile image:',
      'logout_failed': 'Logout failed:',
      
      // Language screen
      'select_language': 'Select Language',
      'choose_language': 'Choose your preferred language',
      
      // Login screen
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'or': 'OR',
      'continue_with_google': 'Continue with Google',
      'dont_have_account': 'Don\'t have an account?',
      'register': 'Register',
      'want_to_help': 'Want to help people?',
      'register_as_volunteer': 'Register as Volunteer',
      'login_successful': 'Login successful!',
      'google_signup': 'Continue with Google',
      
      // Register screen
      'aadhar_id': 'Aadhar ID / Restaurant ID',
      'address': 'Address / Location (Click to detect)',
      'contact': 'Contact Number',
      'about': 'About',
      'org_name': 'Organization Name / Individual',
      'user_type': 'Type',
      'profile_pic': 'Add Profile Picture',
      'change_profile_pic': 'Change Profile Picture',
      'registration_successful': 'Registration successful!',
      'get_address': 'Please get your address by clicking the location button',
      'type': 'Type',
      'contact_number': 'Contact Number',
      
      // Register volunteer screen
      'volunteer_registration': 'Volunteer Registration',
      'full_name': 'Full Name',
      'aadhar_number': 'Aadhar Number',
      'address_click_detect': 'Address (Click to detect)',
      'about_yourself': 'About Yourself',
      'have_vehicle': 'Do you have a vehicle for deliveries?',
      'vehicle_type': 'Vehicle Type',
      'vehicle_number': 'Vehicle Number',
      'driving_license': 'Driving License Image',
      'upload_license': 'Upload License Image',
      
      // Logout
      'logging_out': 'Logging out...',
      'error_logout': 'Error logging out: ',
      
      // Validation messages
      'enter_email': 'Please enter your email',
      'valid_email': 'Please enter a valid email',
      'enter_password': 'Please enter your password',
      'password_length': 'Password must be at least 6 characters',
      'enter_name': 'Please enter your name',
      'enter_id': 'Please enter your ID',
      'enter_contact': 'Please enter your contact number',
      'valid_contact': 'Please enter a valid contact number',
      'enter_about': 'Please enter about yourself',
      'enter_org_name': 'Please enter organization name or individual',
      'select_type': 'Please select a type',
      'select_vehicle_type': 'Please select a vehicle type',
      'enter_vehicle_number': 'Please enter your vehicle number',
      
      // Charity related translations
      'donate_to_charity': 'Donate to Charity',
      'error': 'Error',
      'no_charities_available': 'No Charities Available',
      'check_back_later': 'Check back later for charity donation opportunities',
      'refresh': 'Refresh',
      'make_a_difference': 'Make a Difference',
      'contribution_help': 'Your contribution can help those in need. Choose a charity below to donate.',
      'food_relief': 'Food Relief',
      'from': 'From',
      'make_a_donation': 'Make a Donation',
      'donation_history': 'Donation History',
      'select_amount': 'Select Amount',
      'custom_amount': 'Custom Amount',
      'your_information': 'Your Information',
      'full_name': 'Full Name',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'request_tax_benefits': 'Request Tax Benefits (80G)',
      'pan_card_number': 'PAN Card Number',
      'required_for_tax_benefits': 'Required for tax benefits',
      'payment_method': 'Payment Method',
      'credit_debit_card': 'Credit/Debit Card',
      'net_banking': 'Net Banking',
      'upi_gpay_phonepe': 'UPI / Google Pay / PhonePe',
      'initializing_payment': 'Initializing payment...',
      'processing_donation': 'Processing your donation...',
      'thank_you': 'Thank You!',
      'donation_successful': 'Your donation was successful!',
      'amount': 'Amount',
      'date': 'Date',
      'transaction_id': 'Transaction ID',
      'charity': 'Charity',
      'contribution_difference': 'Your contribution will make a real difference in someone\'s life.',
      'view_history': 'View History',
      'done': 'Done',
      'information_secure': 'Your information is secure and will only be used for donation purposes.',
      'support_our_cause': 'Support our cause',
      
      // Post Donation Screen
      'post_donation': 'Post Donation',
      'refresh_authentication': 'Refresh Authentication',
      'sign_out_sign_in_again': 'Sign Out & Sign In Again',
      'go_to_profile': 'Go to Profile',
      'go_back': 'Go Back',
      'refresh_profile_note': 'Note: If you just registered, please log out and log back in to refresh your profile status.',
      'refresh_status': 'Refresh Status',
      'food_name': 'Food Name',
      'please_enter_food_name': 'Please enter food name',
      'quantity': 'Quantity',
      'please_enter_quantity': 'Please enter quantity',
      'please_enter_valid_number': 'Please enter a valid number',
      'description': 'Description',
      'please_enter_description': 'Please enter description',
      'food_type': 'Food Type',
      'veg': 'Vegetarian',
      'nonveg': 'Non-Vegetarian',
      'jain': 'Jain',
      'please_select_food_type': 'Please select food type',
      'pickup_address_click_detect': 'Pickup Address (Click to detect)',
      'get_current_location': 'Get Current Location',
      'please_get_pickup_address': 'Please get pickup address by clicking the location button',
      'location': 'Location',
      'expiry_date_time': 'Expiry Date & Time',
      'select_expiry_date_time': 'Select expiry date and time',
      'please_select_expiry_date_time': 'Please select a valid expiry date and time',
      'local_time': 'Local time',
      'need_volunteer_for_delivery': 'Need Volunteer for Delivery',
      'volunteer_note': 'Note: When your donation is accepted by a recipient, they will be able to request a volunteer for delivery.',
      'donation_posted_successfully': 'Donation posted successfully!',
      'failed_to_post_donation': 'Failed to post donation. Please try again.',
      'authentication_error_refresh': 'Authentication error: Please sign out and sign in again to refresh your credentials.',
      'authentication_error': 'Authentication Error',
      'auth_error_details': 'Your donor profile could not be verified. This could happen if:\n\n1. You recently registered and your profile is not fully synced\n2. Your authentication token has expired\n\nPlease sign out and sign back in to refresh your credentials.',
      'ok': 'OK',
      'sign_out_now': 'Sign Out Now',
      
      // Donor history translations
      'no_donations_found': 'No donations found',
      'create_donations_to_see': 'Create a donation to see it here',
      'create_donation': 'Create Donation',
      'no_donation_history_found': 'No donation history found. Please try again later.',
      'sign_in_to_view_donations': 'Please sign in to view your donation history.',
      'all': 'All',
      'signed_out': 'Signed Out',
      'sign_out_confirmation': 'Are you sure you want to sign out?',
      'sign_out': 'Sign Out',
      'yes': 'Yes',
      'no': 'No',
      
      // View donations screen
      'available_donations': 'उपलब्ध दाने',
      'filter_donations': 'दान फिल्टर करा',
      'food_type': 'अन्नाचा प्रकार',
      'sort_by': 'याद्वारे क्रमवा',
      'sort_by_expiry': 'कालबाह्य तारीख',
      'sort_by_distance': 'अंतर',
      'sort_by_quantity': 'प्रमाण',
      'maximum_distance': 'कमाल अंतर',
      'km': 'किमी',
      'show_needs_volunteer': 'स्वयंसेवक मदतीची आवश्यकता असलेली दाने दाखवा',
      'reset': 'रीसेट करा',
      'apply_filters': 'फिल्टर लागू करा',
      'search_food': 'अन्न शोधा...',
      'filter': 'फिल्टर',
      'needs_volunteer': 'स्वयंसेवकाची गरज आहे',
      'no_available_donations': 'कोणतीही उपलब्ध दाने सापडली नाहीत',
      'no_results_for': 'यासाठी कोणतेही परिणाम सापडले नाहीत',
      'check_back_later': 'नवीन दानांसाठी नंतर पुन्हा तपासा',
      'try_changing_filters': 'अधिक दाने पाहण्यासाठी तुमचे फिल्टर बदलण्याचा प्रयत्न करा',
      'clear_filters': 'फिल्टर साफ करा',
      'profile_not_found_recipient': 'तुमचे प्रोफाइल सापडले नाही. दाने पाहण्यासाठी तुम्ही प्राप्तकर्ता म्हणून नोंदणीकृत असल्याची खात्री करा.',
      'unable_to_load_donations': 'या वेळी दाने लोड करण्यास अक्षम. कृपया नंतर पुन्हा प्रयत्न करा.',
      'retry': 'पुन्हा प्रयत्न करा',
      'go_to_profile': 'प्रोफाइलवर जा',
      'no_image_available': 'कोणतीही प्रतिमा उपलब्ध नाही',
      'expiring_soon': 'लवकरच कालबाह्य होत आहे',
      'quantity': 'प्रमाण',
      'servings': 'वाटप',
      'tap_to_read_more': 'अधिक वाचण्यासाठी टॅप करा',
      'donor': 'दाता',
      'call_donor': 'दात्यास कॉल करा',
      'get_directions': 'दिशा मिळवा',
      'expires': 'कालबाह्य होते',
      'view_details': 'तपशील पहा',
      'unknown_location': 'अज्ञात स्थान',
      'anonymous': 'अनामित',
      'error': 'त्रुटी',
      'refresh': 'रिफ्रेश करा',
      
      // Recipient history screen
      'filter_donation_history': 'Filter Donation History',
      'time_period': 'Time Period',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'time': 'Time',
      'type': 'Type',
      'accept_donations_to_see': 'Accept donations to see them here',
      'browse_donations': 'Browse Donations',
      'no_donations_match_criteria': 'No donations match your criteria',
      'try_adjusting_filters': 'Try adjusting your filters to see more donations',
      'clear_all_filters': 'Clear All Filters',
      'update_location': 'Update Location',
      'location_updated_donations_refreshed': 'Location updated. Donations refreshed with distance information.',
      'could_not_get_location': 'Could not get your location. Please ensure location services are enabled.',
      'error_updating_location': 'Error updating location',
      'donated_by': 'Donated by',
      'at': 'at',
      'delivery_method': 'Delivery method',
      'self_pickup': 'Self-pickup',
      'add_feedback': 'Add Feedback',
      'edit_feedback': 'Edit Feedback',
      'your_feedback': 'Your Feedback',
      'share_experience_hint': 'Share your experience about this donation...',
      'feedback_submitted_successfully': 'Feedback submitted successfully!',
      'error_submitting_feedback': 'Error submitting feedback',
      'distance': 'Distance',
      'submit': 'Submit',
      
      // Donation detail screen
      'donation_details': 'Donation Details',
      'unknown_food': 'Unknown Food',
      'no_description_available': 'No description available',
      'unknown': 'Unknown',
      'servings': 'servings',
      'anonymous_donor': 'Anonymous Donor',
      'donor_information': 'Donor Information',
      'donor': 'Donor',
      'location': 'Location',
      'food_description': 'Food Description',
      'expires': 'Expires',
      'exact_expiry': 'Exact expiry',
      'delivery_options': 'Delivery Options',
      'need_volunteer_assistance': 'Need volunteer assistance?',
      'yes_request_volunteer': 'Yes, request volunteer help for delivery',
      'no_pickup_myself': 'No, I will pick up this donation myself',
      'changed_from_original': 'You changed this from the donor\'s original setting',
      'using_donor_preference': 'Using donor\'s preferred delivery option',
      'accept_donation': 'Accept this donation',
      'donation_accepted_with_volunteer': 'Donation accepted successfully. A volunteer will assist with delivery.',
      'donation_accepted_self_pickup': 'Donation accepted successfully. You will need to collect this yourself.',
    },
    'hi': {
      // Common strings
      'app_name': 'काइंडमील्स',
      'app_slogan': 'भोजन बांटें, प्यार बांटें',
      'get_started': 'शुरू करें',
      'continue': 'जारी रखें',
      'inspirational_quote': 'जब हम खुशी से देते हैं और कृतज्ञता से स्वीकार करते हैं, तो हर कोई आशीर्वादित होता है।',
      'no_image_available': 'कोई छवि उपलब्ध नहीं',
      
      // Motivational content
      'feed_smile': 'आज एक मुस्कान खिलाएं',
      'meal_brighten': 'एक भोजन किसी के पूरे दिन को उज्जवल कर सकता है',
      'share_table': 'अपनी मेज साझा करें',
      'no_hunger': 'आमच्या समुदायात कोणीही भुकेले राहू नये',
      'food_waste': 'अन्न वाया जाणे ते अन्न स्वाद',
      'rescue_food': 'अतिरिक्त भोजन को बचाएं और गरजूंना खाऊ घाला',
      
      // Social Media Footer
      'privacy_policy': 'गोपनीयता नीति',
      // Dashboard screen
      'welcome_to': 'आपका स्वागत है',
      'top_volunteers': 'शीर्ष स्वयंसेवक',
      'top_donors': 'शीर्ष दानदाता',
      'view_full_leaderboard': 'पूरा लीडरबोर्ड देखें',
      'reviews_feedback': 'समीक्षाएँ और प्रतिक्रिया',
      'view_all_reviews': 'सभी समीक्षाएँ देखें',
      'support_a_cause': 'एक कारण का समर्थन करें',
      'donate_to_kindmeals': 'काइंडमील्स को दान करें',
      'donate_subtitle': 'खाद्य अपशिष्ट और भूख को कम करने के हमारे मिशन का समर्थन करें',
      'donate_now': 'अभी दान करें',
      'view_all_charities': 'सभी दान संस्थाएँ देखें',
      'name': 'नाम',
      'deliveries': 'डिलिवरी',
      'meals': 'भोजन',
      'no_volunteers_found': 'कोई स्वयंसेवक नहीं मिला',
      'no_donors_found': 'कोई दानदाता नहीं मिला',
      'refresh_data': 'डेटा रीफ्रेश करें',
      
      // Volunteers Screen
      'volunteers': 'स्वयंसेवक',
      'volunteer_leaderboard': 'स्वयंसेवक लीडरबोर्ड',
      'total_volunteers': 'कुल स्वयंसेवक',
      'total_deliveries': 'कुल डिलिवरी',
      'avg_deliveries': 'औसत डिलिवरी',
      'rank': 'रैंक',
      'volunteer': 'स्वयंसेवक',
      'deliveries_made': 'डिलिवरी की गई',
      'become_volunteer': 'स्वयंसेवक बनें',
      
      // Motivational content
      'feed_smile': 'आज एक मुस्कान खिलाएं',
      'meal_brighten': 'एक भोजन किसी के पूरे दिन को उज्जवल कर सकता है',
      'share_table': 'अपनी मेज साझा करें',
      'no_hunger': 'आमच्या समुदायात कोणीही भुकेले राहू नये',
      'food_waste': 'अन्न वाया जाणे ते अन्न स्वाद',
      'rescue_food': 'अतिरिक्त भोजन को बचाएं और गरजूंना खाऊ घाला',
      'donate_what': 'जो दे सकते हैं, दान करें',
      'every_contribution': 'हर योगदान फरक लाता है',
      'hunger_stat': '9 में से 1 व्यक्ति भूखा रहता है',
      'change_stat': 'आपका दान इस आंकड़े को बदल सकता है',
      
      // Social Media Footer
      'privacy_policy': 'गोपनीयता नीति',
      'terms_of_service': 'सेवा की शर्तें',
      'contact_us': 'संपर्क करें',
      'all_rights_reserved': '© 2025 काइंडमील्स. सर्वाधिकार सुरक्षित.',
      
      // Profile Screen
      'profile': 'प्रोफ़ाइल',
      'try_again': 'पुन: प्रयास करें',
      'edit': 'संपादित करें',
      'logout': 'लॉग आउट',
      'logout_confirm': 'क्या आप लॉग आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'error_loading_profile': 'प्रोफ़ाइल लोड करने में त्रुटि',
      'change_language': 'भाषा बदलें',
      'personal_information': 'व्यक्तिगत जानकारी',
      'contact_information': 'संपर्क जानकारी',
      'organization_information': 'संगठन की जानकारी',
      'about': 'परिचय',
      'full_name': 'पूर्ण नाम',
      'email_address': 'ईमेल पत्ता',
      'contact_number': 'संपर्क नंबर',
      'address': 'पता',
      'organization_name': 'संगठन का नाम',
      'organization_id': 'संगठन आईडी',
      'description': 'विवरण',
      'no_description': 'कोई विवरण उपलब्ध नहीं',
      'profile_image_updated': 'प्रोफाइल छवि सफलतापूर्वक अपडेट की गई',
      'failed_upload_image': 'प्रोफाइल छवि अपलोड करने में विफल:',
      'logout_failed': 'लॉगआउट विफल:',
      
      // Language screen
      'select_language': 'भाषा चुनें',
      'choose_language': 'अपनी पसंतीदा भाषा चुनें',
      
      // Login screen
      'login': 'लॉगिन करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'or': 'या',
      'continue_with_google': 'Google के साथ जारी रखें',
      'dont_have_account': 'खाता नहीं है?',
      'register': 'रजिस्टर करें',
      'want_to_help': 'लोगों की मदद करना चाहते हैं?',
      'register_as_volunteer': 'स्वयंसेवक के रूप में रजिस्टर करें',
      'login_successful': 'लॉगिन सफल!',
      'google_signup': 'Google के साथ जारी रखें',
      
      // Register screen
      'aadhar_id': 'आधार आईडी / रेस्टॉरेंट आईडी',
      'address': 'पत्ता / स्थान (पता लगाने के लिए क्लिक करें)',
      'contact': 'संपर्क नंबर',
      'about': 'परिचय',
      'org_name': 'संगठन का नाम / व्यक्तिगत',
      'user_type': 'प्रकार',
      'profile_pic': 'प्रोफाइल चित्र जोड़ें',
      'change_profile_pic': 'प्रोफाइल चित्र बदलें',
      'registration_successful': 'पंजीकरण सफल!',
      'get_address': 'कृपया स्थान बटन पर क्लिक करके अपना पता प्राप्त करें',
      'type': 'प्रकार',
      'contact_number': 'संपर्क नंबर',
      
      // Register volunteer screen
      'volunteer_registration': 'स्वयंसेवक पंजीकरण',
      'full_name': 'पूर्ण नाम',
      'aadhar_number': 'आधार नंबर',
      'address_click_detect': 'पत्ता (पता लगाने के लिए क्लिक करें)',
      'about_yourself': 'अपने बारे में',
      'have_vehicle': 'क्या आपके पास डिलीवरी के लिए वाहन है?',
      'vehicle_type': 'वाहन प्रकार',
      'vehicle_number': 'वाहन नंबर',
      'driving_license': 'ड्राइविंग लाइसेंस छवि',
      'upload_license': 'लाइसेंस छवि अपलोड करें',
      
      // Logout
      'logging_out': 'लॉग आउट हो रहा है...',
      'error_logout': 'लॉग आउट में त्रुटी: ',
      
      // Validation messages
      'enter_email': 'कृपया अपना ईमेल दर्ज करें',
      'valid_email': 'कृपया वैध ईमेल दर्ज करें',
      'enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
      'password_length': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
      'enter_name': 'कृपया अपना नाम दर्ज करें',
      'enter_id': 'कृपया अपना आईडी दर्ज करें',
      'enter_contact': 'कृपया अपना संपर्क नंबर दर्ज करें',
      'valid_contact': 'कृपया एक वैध संपर्क नंबर दर्ज करें',
      'enter_about': 'कृपया अपने बारे में जानकारी दर्ज करें',
      'enter_org_name': 'कृपया संगठन का नाम या व्यक्तिगत दर्ज करें',
      'select_type': 'कृपया एक प्रकार चुनें',
      'select_vehicle_type': 'कृपया एक वाहन प्रकार चुनें',
      'enter_vehicle_number': 'कृपया अपना वाहन नंबर दर्ज करें',
      
      // Charity related translations
      'donate_to_charity': 'दान करा',
      'error': 'त्रुटी',
      'no_charities_available': 'कोणतीही धर्मादाय संस्था उपलब्ध नाही',
      'check_back_later': 'दान संधींसाठी नंतर पुन्हा तपासा',
      'refresh': 'रिफ्रेश करा',
      'make_a_difference': 'फरक घडवा',
      'contribution_help': 'तुमचे योगदान गरजूंना मदत करू शकते. दान करण्यासाठी खालील एक धर्मादाय संस्था निवडा.',
      'food_relief': 'अन्न मदत',
      'from': 'पासून',
      'make_a_donation': 'दान करा',
      'donation_history': 'दान इतिहास',
      'select_amount': 'रक्कम निवडा',
      'custom_amount': 'इतर रक्कम',
      'your_information': 'तुमची माहिती',
      'full_name': 'पूर्ण नाव',
      'email': 'ईमेल',
      'phone_number': 'फोन नंबर',
      'request_tax_benefits': 'कर लाभ (80G) ची विनंती करा',
      'pan_card_number': 'पॅन कार्ड नंबर',
      'required_for_tax_benefits': 'कर लाभांसाठी आवश्यक',
      'payment_method': 'पेमेंट पद्धत',
      'credit_debit_card': 'क्रेडिट/डेबिट कार्ड',
      'net_banking': 'नेट बँकिंग',
      'upi_gpay_phonepe': 'यूपीआय / गुगल पे / फोन पे',
      'initializing_payment': 'पेमेंट सुरू होत आहे...',
      'processing_donation': 'तुमचे दान प्रक्रिया करत आहे...',
      'thank_you': 'धन्यवाद!',
      'donation_successful': 'तुमचे दान यशस्वी झाले!',
      'amount': 'रक्कम',
      'date': 'तारीख',
      'transaction_id': 'व्यवहार आयडी',
      'charity': 'चैरिटी',
      'contribution_difference': 'तुमचे योगदान कुणाच्या जीवनात खरा फरक घडवेल.',
      'view_history': 'इतिहास पहा',
      'done': 'झाले',
      'information_secure': 'तुमची माहिती सुरक्षित आहे आणि फक्त दान उद्देशांसाठी वापरली जाईल.',
      'support_our_cause': 'आमच्या मिशनला पाठिंबा द्या',
      
      // Post Donation Screen
      'post_donation': 'दान पोस्ट करें',
      'refresh_authentication': 'प्रमाणीकरण रीफ्रेश करें',
      'sign_out_sign_in_again': 'साइन आउट करें आणि पुन्हा साइन इन करा.',
      'go_to_profile': 'प्रोफाइलवर जा',
      'go_back': 'मागे जा',
      'refresh_profile_note': 'टीप: तुम्ही नुकतीच नोंदणी केली असल्यास, तुमची प्रोफाइल स्थिती रिफ्रेश करण्यासाठी कृपया लॉग आउट करा आणि पुन्हा लॉग इन करा.',
      'refresh_status': 'स्थिति रीफ्रेश करें',
      'food_name': 'अन्नाचे नाव',
      'please_enter_food_name': 'कृपया अन्नाचे नाव प्रविष्ट करा',
      'quantity': 'मात्रा',
      'please_enter_quantity': 'कृपया मात्रा दर्ज करें',
      'please_enter_valid_number': 'कृपया वैध संख्या प्रविष्ट करा',
      'description': 'वर्णन',
      'please_enter_description': 'कृपया वर्णन प्रविष्ट करा',
      'food_type': 'अन्नाचा प्रकार',
      'veg': 'शाकाहारी',
      'nonveg': 'मांसाहारी',
      'jain': 'जैन',
      'please_select_food_type': 'कृपया अन्नाचा प्रकार निवडा',
      'pickup_address_click_detect': 'पिकअप पत्ता (शोधण्यासाठी क्लिक करा)',
      'get_current_location': 'वर्तमान स्थान मिळवा',
      'please_get_pickup_address': 'कृपया स्थान बटनावर क्लिक करून पिकअप पत्ता मिळवा',
      'location': 'स्थान',
      'expiry_date_time': 'समाप्ती तारीख आणि वेळ',
      'select_expiry_date_time': 'समाप्ती तारीख आणि वेळ निवडा',
      'please_select_expiry_date_time': 'कृपया वैध समाप्ती तारीख आणि वेळ निवडा',
      'local_time': 'स्थानिक वेळ',
      'need_volunteer_for_delivery': 'वितरणासाठी स्वयंसेवकाची आवश्यकता आहे',
      'volunteer_note': 'टीप: जेव्हा तुमचे दान एखाद्या प्राप्तकर्त्याने स्वीकारले जाते, तेव्हा त्यांना वितरणासाठी स्वयंसेवकाची विनंती करता येईल.',
      'donation_posted_successfully': 'दान यशस्वीरित्या पोस्ट केले!',
      'failed_to_post_donation': 'दान पोस्ट करण्यात अयशस्वी. कृपया पुन्हा प्रयास करा.',
      'authentication_error_refresh': 'प्रमाणीकरण त्रुटी: कृपया अपने क्रेडेंशियल्स को रीफ्रेश करने के लिए साइन आउट करें और फिर से साइन इन करें।',
      'authentication_error': 'प्रमाणीकरण त्रुटी',
      'auth_error_details': 'आपकी दाता प्रोफ़ाइल सत्यापित नहीं की जा सकी। ऐसा हो सकता है:\n\n1. आपने हाल ही में पंजीकरण किया है और आपकी प्रोफ़ाइल पूरी तरह से सिंक नहीं हुई है\n2. आपका प्रमाणीकरण टोकन समाप्त हो गया है\n\nकृपया अपने क्रेडेंशियल्स को रीफ्रेश करने के लिए साइन आउट करें और फिर से साइन इन करें।',
      'ok': 'ठीक है',
      'sign_out_now': 'अभी साइन आउट करें',
      
      // Charity donation screen
      'donate': 'दान करा',
      'select_amount': 'रक्कम निवडा',
      'custom_amount': 'इतर रक्कम',
      'payment_method': 'पेमेंट पद्धत',
      'upi': 'यूपीआई',
      'card': 'क्रेडिट/डेबिट कार्ड',
      'net_banking': 'नेट बँकिंग',
      'enter_valid_amount': 'कृपया वैध रक्कम प्रविष्ट करा',
      'amount_must_be_greater': 'रक्कम 10 पेक्षा जास्त असावी',
      'select_payment_method': 'कृपया पेमेंट पद्धत निवडा',
      'donate_caps': 'दान करा',
      
      // Donor history translations
      'no_donations_found': 'कोणतेही दान सापडले नाही',
      'create_donations_to_see': 'येथे पाहण्यासाठी दान करा',
      'create_donation': 'दान करा',
      'no_donation_history_found': 'कोई दान इतिहास नहीं मिला। कृपया बाद में फिर से प्रयास करें।',
      'sign_in_to_view_donations': 'अपने दान इतिहास को देखने के लिए कृपया साइन इन करें।',
      'all': 'सभी',
      
      // View donations screen
      'available_donations': 'उपलब्ध दाने',
      'filter_donations': 'दान फिल्टर करा',
      'food_type': 'अन्नाचा प्रकार',
      'sort_by': 'याद्वारे क्रमवा',
      'sort_by_expiry': 'कालबाह्य तारीख',
      'sort_by_distance': 'अंतर',
      'sort_by_quantity': 'प्रमाण',
      'maximum_distance': 'कमाल अंतर',
      'km': 'किमी',
      'show_needs_volunteer': 'स्वयंसेवक मदतीची आवश्यकता असलेली दाने दाखवा',
      'reset': 'रीसेट करा',
      'apply_filters': 'फिल्टर लागू करा',
      'search_food': 'अन्न शोधा...',
      'filter': 'फिल्टर',
      'needs_volunteer': 'स्वयंसेवकाची गरज आहे',
      'no_available_donations': 'कोणतीही उपलब्ध दाने सापडली नाहीत',
      'no_results_for': 'यासाठी कोणतेही परिणाम सापडले नाहीत',
      'check_back_later': 'नवीन दानांसाठी नंतर पुन्हा तपासा',
      'try_changing_filters': 'अधिक दाने पाहण्यासाठी तुमचे फिल्टर बदलण्याचा प्रयत्न करा',
      'clear_filters': 'फिल्टर साफ करा',
      'profile_not_found_recipient': 'तुमचे प्रोफाइल सापडले नाही. दाने पाहण्यासाठी तुम्ही प्राप्तकर्ता म्हणून नोंदणीकृत असल्याची खात्री करा.',
      'unable_to_load_donations': 'या वेळी दाने लोड करण्यास अक्षम. कृपया नंतर पुन्हा प्रयत्न करा.',
      'retry': 'पुन्हा प्रयत्न करा',
      'go_to_profile': 'प्रोफाइलवर जा',
      'no_image_available': 'कोणतीही प्रतिमा उपलब्ध नाही',
      'expiring_soon': 'लवकरच कालबाह्य होत आहे',
      'quantity': 'प्रमाण',
      'servings': 'वाटप',
      'tap_to_read_more': 'अधिक वाचण्यासाठी टॅप करा',
      'donor': 'दाता',
      'call_donor': 'दात्यास कॉल करा',
      'get_directions': 'दिशा मिळवा',
      'expires': 'कालबाह्य होते',
      'view_details': 'तपशील पहा',
      'unknown_location': 'अज्ञात स्थान',
      'anonymous': 'अनामित',
      'error': 'त्रुटी',
      'refresh': 'रिफ्रेश करा',
      
      // Recipient history screen (Hindi)
      'recipient_history': 'प्राप्तकर्ता इतिहास',
      'my_recipient_history': 'मेरा प्राप्तकर्ता इतिहास',
      'donations_accepted': 'स्वीकृत दान',
      'no_accepted_donations': 'कोई स्वीकृत दान नहीं',
      'accept_a_donation': 'एक दान स्वीकारें',
      'filter_history': 'इतिहास फ़िल्टर करें',
      'meals_received': 'प्राप्त भोजन',
      'request_volunteer': 'स्वयंसेवक का अनुरोध करें',
      'volunteer_requested': 'स्वयंसेवक का अनुरोध किया गया',
      'cancel_volunteer_request': 'स्वयंसेवक अनुरोध रद्द करें',
      'pickup_yourself': 'स्वयं पिकअप करें',
      'volunteer_confirmed': 'स्वयंसेवक की पुष्टि की गई',
      'volunteer_name': 'स्वयंसेवक का नाम',
      'volunteer_phone': 'स्वयंसेवक का फोन',
      'confirm_receipt': 'रसीद की पुष्टि करें',
      'confirm_receipt_question': 'क्या आप पुष्टि करना चाहते हैं कि आपने दान प्राप्त कर लिया है?',
      'yes_received': 'हां, प्राप्त किया',
      'not_yet': 'अभी नहीं',
      'receipt_confirmed': 'रसीद की पुष्टि की गई',
      'add_review': 'समीक्षा जोड़ें',
      'view_receipt_details': 'रसीद विवरण देखें',
      
      // Recipient history screen (old translations - keep for compatibility)
      'filter_donation_history': 'दान इतिहास फ़िल्टर करें',
      'time_period': 'समय अवधि',
      'today': 'आज',
      'yesterday': 'कल',
      'days_ago': 'दिन पहले',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'time': 'समय',
      'type': 'प्रकार',
      'accept_donations_to_see': 'यहां देखने के लिए दान स्वीकार करें',
      'browse_donations': 'दान ब्राउज़ करें',
      'no_donations_match_criteria': 'कोई दान आपके मानदंडों से मेल नहीं खाता',
      'try_adjusting_filters': 'अधिक दान देखने के लिए अपने फिल्टर समायोजित करने का प्रयास करें',
      'clear_all_filters': 'सभी फिल्टर साफ़ करें',
      'update_location': 'स्थान अपडेट करें',
      'no_donations_found': 'कोई दान इतिहास नहीं मिला',
      'create_donations_to_see': 'यहां देखने के लिए दान बनाएं',
      'create_donation': 'दान बनाएं',
      'all': 'सभी',
      'active': 'सक्रिय',
      'accepted': 'स्वीकृत',
      'expired': 'समाप्त',
      'search_food_by_name': 'भोजन का नाम खोजें...',
      'no_filtered_donations_found': 'कोई {0} दान नहीं मिला',
      'no_search_results_found': '"{0}" के लिए कोई परिणाम नहीं मिला',
      'unknown': 'अज्ञात',
      'created': 'बनाया गया',
      'expires': 'समाप्त होता है',
      'tap_to_read_more': 'अधिक पढ़ने के लिए टैप करें',
      'close': 'बंद करें',
      'accepted_by': 'स्वीकारकर्ता',
      'accepted_on': 'स्वीकृति तिथि',
      'expired_on': 'समाप्ति तिथि',
      'signed_out': 'साइन आउट किया गया',
      'sign_out_confirmation': 'क्या आप साइन आउट करना चाहते हैं?',
      'sign_out': 'साइन आउट',
      'yes': 'हां',
      'no': 'नहीं',
      'ok': 'ठीक है',
      'sign_out_now': 'अभी साइन आउट करें',
      
      // Recipient history screen
      'recipient_history': 'प्राप्तकर्ता इतिहास',
      'my_recipient_history': 'माझा प्राप्तकर्ता इतिहास',
      'donations_accepted': 'स्वीकारलेली दाने',
      'no_accepted_donations': 'कोणतीही स्वीकारलेली दाने नाहीत',
      'accept_a_donation': 'दान स्वीकारा',
      'filter_history': 'इतिहास फिल्टर करा',
      'meals_received': 'प्राप्त केलेली जेवणे',
      'unknown_location': 'अज्ञात स्थान',
      'anonymous': 'अनामित',
      'get_directions': 'दिशा मिळवा',
      'request_volunteer': 'स्वयंसेवकाची विनंती करा',
      'volunteer_requested': 'स्वयंसेवकाची विनंती केली',
      'cancel_volunteer_request': 'स्वयंसेवक विनंती रद्द करा',
      'pickup_yourself': 'स्वतः पिकअप करें',
      'volunteer_confirmed': 'स्वयंसेवक निश्चित केला',
      'volunteer_name': 'स्वयंसेवक का नाम',
      'volunteer_phone': 'स्वयंसेवक का फोन',
      'confirm_receipt': 'प्राप्ती निश्चित करा',
      'confirm_receipt_question': 'तुम्ही दान प्राप्त केल्याची पुष्टी करू इच्छिता?',
      'yes_received': 'होय, प्राप्त केले',
      'not_yet': 'अजून नाही',
      'receipt_confirmed': 'प्राप्ती निश्चित केली',
      'add_review': 'परीक्षण जोडा',
      'view_receipt_details': 'प्राप्ती तपशील पहा',
      'distance': 'दूरी',
      'submit': 'सबमिट करा',
      
      // Donation detail screen
      'donation_details': 'दान विवरण',
      'unknown_food': 'अज्ञात अन्न',
      'no_description_available': 'कोणतेही वर्णन उपलब्ध नाही',
      'unknown': 'अज्ञात',
      'servings': 'वाटप',
      'anonymous_donor': 'अनामित दाता',
      'donor_information': 'दात्याची माहिती',
      'donor': 'दाता',
      'location': 'स्थान',
      'food_description': 'अन्न वर्णन',
      'expires': 'कालबाह्य होते',
      'exact_expiry': 'नेमकी कालबाह्यता',
      'delivery_options': 'वितरण पर्याय',
      'need_volunteer_assistance': 'स्वयंसेवक मदत हवी आहे?',
      'yes_request_volunteer': 'होय, वितरणासाठी स्वयंसेवक मदत विनंती करा',
      'no_pickup_myself': 'नाही, मी हे दान स्वतः घेऊन जाईन',
      'changed_from_original': 'तुम्ही हे दात्याच्या मूळ सेटिंगमधून बदलले आहे',
      'using_donor_preference': 'दात्याचा पसंतीचा वितरण पर्याय वापरत आहे',
      'accept_donation': 'हे दान स्वीकारा',
      'donation_accepted_with_volunteer': 'दान यशस्वीरीत्या स्वीकारले. एक स्वयंसेवक वितरणासाठी मदत करेल.',
      'donation_accepted_self_pickup': 'दान यशस्वीरीत्या स्वीकारले. तुम्हाला हे स्वतः संकलित करावे लागेल.',
    },
    'mr': {
      // Common strings
      'app_name': 'काइंडमील्स',
      'app_slogan': 'अन्न वाटा, प्रेम वाटा',
      'get_started': 'सुरु करा',
      'continue': 'पुढे चला',
      'inspirational_quote': 'जेव्हा आपण आनंदाने देतो आणि कृतज्ञतेने स्वीकारतो, तेव्हा प्रत्येकाला आशीर्वाद मिळतो.',
      'no_image_available': 'कोणतीही प्रतिमा उपलब्ध नाही',
      
      // Dashboard screen
      'welcome_to': 'आपले स्वागत आहे',
      'top_volunteers': 'शीर्ष स्वयंसेवक',
      'top_donors': 'शीर्ष दानशूर',
      'view_full_leaderboard': 'संपूर्ण लीडरबोर्ड पहा',
      'reviews_feedback': 'परीक्षण आणि अभिप्राय',
      'view_all_reviews': 'सर्व परीक्षणे पहा',
      'support_a_cause': 'एका कारणाचे समर्थन करा',
      'donate_to_kindmeals': 'काइंडमील्सला दान करा',
      'donate_subtitle': 'अन्न वाया जाणे आणि भूक कमी करण्याच्या आमच्या मिशनला समर्थन द्या',
      'donate_now': 'आता दान करा',
      'view_all_charities': 'सर्व धर्मादाय संस्था पहा',
      'name': 'नाव',
      'deliveries': 'वितरण',
      'meals': 'जेवणे',
      'no_volunteers_found': 'कोई स्वयंसेवक नहीं मिला',
      'no_donors_found': 'कोई दानशूर सापडले नाहीत',
      'refresh_data': 'डेटा रिफ्रेश करा',
      
      // Volunteers Screen
      'volunteers': 'स्वयंसेवक',
      'volunteer_leaderboard': 'स्वयंसेवक लीडरबोर्ड',
      'total_volunteers': 'एकूण स्वयंसेवक',
      'total_deliveries': 'एकूण वितरण',
      'avg_deliveries': 'सरासरी वितरण',
      'rank': 'क्रमांक',
      'volunteer': 'स्वयंसेवक',
      'deliveries_made': 'वितरण केले',
      'become_volunteer': 'स्वयंसेवक व्हा',
      
      // Motivational content
      'feed_smile': 'आज एक हास्य द्या',
      'meal_brighten': 'एक भोजन किसी के पूरे दिन को उज्जवल कर सकता है',
      'share_table': 'तुमची मेज शेअर करा',
      'no_hunger': 'आमच्या समुदायात कोणीही भुकेले राहू नये',
      'food_waste': 'अन्न वाया जाणे ते अन्न स्वाद',
      'rescue_food': 'अतिरिक्त भोजन को बचाएं और गरजूंना खाऊ घाला',
      'donate_what': 'जे देऊ शकता ते दान करा',
      'every_contribution': 'प्रत्येक योगदान फरक करते',
      'hunger_stat': '9 में से 1 व्यक्ति भूखा रहता है',
      'change_stat': 'तुमचे दान हे आकडेवारी बदलू शकते',
      
      // Social Media Footer
      'privacy_policy': 'गोपनीयता धोरण',
      'terms_of_service': 'सेवा की शर्तें',
      'contact_us': 'संपर्क करें',
      'all_rights_reserved': '© 2025 काइंडमील्स. सर्वाधिकार सुरक्षित.',
      
      // Profile Screen
      'profile': 'प्रोफाइल',
      'try_again': 'पुन्हा प्रयत्न करा',
      'edit': 'संपादित करें',
      'logout': 'लॉग आउट',
      'logout_confirm': 'तुम्हाला लॉग आउट करायचे आहे का?',
      'cancel': 'रद्द करा',
      'error_loading_profile': 'प्रोफाइल लोड करताना त्रुटी',
      'change_language': 'भाषा बदलें',
      'personal_information': 'वैयक्तिक माहिती',
      'contact_information': 'संपर्क जानकारी',
      'organization_information': 'संगठन की जानकारी',
      'about': 'परिचय',
      'full_name': 'पूर्ण नाम',
      'email_address': 'ईमेल पत्ता',
      'contact_number': 'संपर्क नंबर',
      'address': 'पता',
      'organization_name': 'संगठन का नाम',
      'organization_id': 'संगठन आईडी',
      'description': 'विवरण',
      'no_description': 'कोई विवरण उपलब्ध नहीं',
      'profile_image_updated': 'प्रोफाइल प्रतिमा यशस्वीरित्या अपडेट केली',
      'failed_upload_image': 'प्रोफाइल प्रतिमा अपलोड करण्यात अयशस्वी:',
      'logout_failed': 'लॉगआउट विफल:',
      
      // Language screen
      'select_language': 'भाषा निवडा',
      'choose_language': 'तुमची पसंतीदा भाषा निवडा',
      
      // Login screen
      'login': 'लॉगिन करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड विसरलात?',
      'or': 'किंवा',
      'continue_with_google': 'Google सह पुढे चला',
      'dont_have_account': 'खाते नाही?',
      'register': 'नोंदणी करा',
      'want_to_help': 'लोकांना मदत करू इच्छिता?',
      'register_as_volunteer': 'स्वयंसेवक म्हणून नोंदणी करा',
      'login_successful': 'लॉगिन यशस्वी!',
      'google_signup': 'Google सह पुढे चला',
      
      // Register screen
      'aadhar_id': 'आधार आईडी / रेस्टॉरेंट आईडी',
      'address': 'पत्ता / स्थान (पता लगाने के लिए क्लिक करें)',
      'contact': 'संपर्क नंबर',
      'about': 'परिचय',
      'org_name': 'संगठन का नाम / व्यक्तिगत',
      'user_type': 'प्रकार',
      'profile_pic': 'प्रोफाइल चित्र जोड़ें',
      'change_profile_pic': 'प्रोफाइल चित्र बदलें',
      'registration_successful': 'पंजीकरण सफल!',
      'get_address': 'कृपया स्थान बटनावर क्लिक करके अपना पता प्राप्त करें',
      'type': 'प्रकार',
      'contact_number': 'संपर्क नंबर',
      
      // Register volunteer screen
      'volunteer_registration': 'स्वयंसेवक पंजीकरण',
      'full_name': 'पूर्ण नाम',
      'aadhar_number': 'आधार नंबर',
      'address_click_detect': 'पत्ता (पता लगाने के लिए क्लिक करें)',
      'about_yourself': 'अपने बारे में',
      'have_vehicle': 'क्या आपके पास डिलीवरी के लिए वाहन है?',
      'vehicle_type': 'वाहन प्रकार',
      'vehicle_number': 'वाहन नंबर',
      'driving_license': 'ड्रायव्हिंग लाइसेंस छवि',
      'upload_license': 'लाइसेंस छवि अपलोड करें',
      
      // Logout
      'logging_out': 'लॉग आउट होत आहे...',
      'error_logout': 'लॉग आउट करताना त्रुटी: ',
      
      // Validation messages
      'enter_email': 'कृपया तुमचा ईमेल दर्ज करें',
      'valid_email': 'कृपया वैध ईमेल दर्ज करें',
      'enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
      'password_length': 'पासवर्ड किमान 6 वर्ण असावा',
      'enter_name': 'कृपया तुमचे नाव प्रविष्ट करा',
      'enter_id': 'कृपया तुमचा आयडी प्रविष्ट करा',
      'enter_contact': 'कृपया तुमचा संपर्क क्रमांक प्रविष्ट करा',
      'valid_contact': 'कृपया वैध संपर्क क्रमांक प्रविष्ट करा',
      'enter_about': 'कृपया अपने बारे में जानकारी दर्ज करें',
      'enter_org_name': 'कृपया संगठन का नाम या व्यक्तिगत दर्ज करें',
      'select_type': 'कृपया एक प्रकार निवडा',
      'select_vehicle_type': 'कृपया एक वाहन प्रकार निवडा',
      'enter_vehicle_number': 'कृपया अपना वाहन नंबर दर्ज करें',
      
      // Charity related translations
      'donate_to_charity': 'दान करा',
      'error': 'त्रुटी',
      'no_charities_available': 'कोणतीही धर्मादाय संस्था उपलब्ध नाही',
      'check_back_later': 'दान संधींसाठी नंतर पुन्हा तपासा',
      'refresh': 'रिफ्रेश करा',
      'make_a_difference': 'फरक घडवा',
      'contribution_help': 'तुमचे योगदान गरजूंना मदत करू शकते. दान करण्यासाठी खालील एक धर्मादाय संस्था निवडा.',
      'food_relief': 'अन्न मदत',
      'from': 'पासून',
      'make_a_donation': 'दान करा',
      'donation_history': 'दान इतिहास',
      'select_amount': 'रक्कम निवडा',
      'custom_amount': 'इतर रक्कम',
      'your_information': 'तुमची माहिती',
      'full_name': 'पूर्ण नाव',
      'email': 'ईमेल',
      'phone_number': 'फोन नंबर',
      'request_tax_benefits': 'कर लाभ (80G) ची विनंती करा',
      'pan_card_number': 'पॅन कार्ड नंबर',
      'required_for_tax_benefits': 'कर लाभांसाठी आवश्यक',
      'payment_method': 'पेमेंट पद्धत',
      'credit_debit_card': 'क्रेडिट/डेबिट कार्ड',
      'net_banking': 'नेट बँकिंग',
      'upi_gpay_phonepe': 'यूपीआय / गुगल पे / फोन पे',
      'initializing_payment': 'पेमेंट सुरू होत आहे...',
      'processing_donation': 'तुमचे दान प्रक्रिया करत आहे...',
      'thank_you': 'धन्यवाद!',
      'donation_successful': 'तुमचे दान यशस्वी झाले!',
      'amount': 'रक्कम',
      'date': 'तारीख',
      'transaction_id': 'व्यवहार आयडी',
      'charity': 'धर्मादाय संस्था',
      'contribution_difference': 'तुमचे योगदान कुणाच्या जीवनात खरा फरक घडवेल.',
      'view_history': 'इतिहास पहा',
      'done': 'झाले',
      'information_secure': 'तुमची माहिती सुरक्षित आहे आणि फक्त दान उद्देशांसाठी वापरली जाईल.',
      'support_our_cause': 'आमच्या मिशनला पाठिंबा द्या',
      
      // Post Donation Screen
      'post_donation': 'दान पोस्ट करें',
      'refresh_authentication': 'प्रमाणीकरण रीफ्रेश करें',
      'sign_out_sign_in_again': 'साइन आउट करें आणि पुन्हा साइन इन करा.',
      'go_to_profile': 'प्रोफाइलवर जा',
      'go_back': 'मागे जा',
      'refresh_profile_note': 'टीप: तुम्ही नुकतीच नोंदणी केली असल्यास, तुमची प्रोफाइल स्थिती रिफ्रेश करण्यासाठी कृपया लॉग आउट करा आणि पुन्हा लॉग इन करा.',
      'refresh_status': 'स्थिति रीफ्रेश करें',
      'food_name': 'अन्नाचे नाव',
      'please_enter_food_name': 'कृपया अन्नाचे नाव प्रविष्ट करा',
      'quantity': 'मात्रा',
      'please_enter_quantity': 'कृपया मात्रा दर्ज करें',
      'please_enter_valid_number': 'कृपया वैध संख्या प्रविष्ट करा',
      'description': 'वर्णन',
      'please_enter_description': 'कृपया वर्णन प्रविष्ट करा',
      'food_type': 'अन्नाचा प्रकार',
      'veg': 'शाकाहारी',
      'nonveg': 'मांसाहारी',
      'jain': 'जैन',
      'please_select_food_type': 'कृपया अन्नाचा प्रकार निवडा',
      'pickup_address_click_detect': 'पिकअप पत्ता (शोधण्यासाठी क्लिक करा)',
      'get_current_location': 'वर्तमान स्थान मिळवा',
      'please_get_pickup_address': 'कृपया स्थान बटनावर क्लिक करून पिकअप पत्ता मिळवा',
      'location': 'स्थान',
      'expiry_date_time': 'समाप्ती तारीख आणि वेळ',
      'select_expiry_date_time': 'समाप्ती तारीख आणि वेळ निवडा',
      'please_select_expiry_date_time': 'कृपया वैध समाप्ती तारीख आणि वेळ निवडा',
      'local_time': 'स्थानिक वेळ',
      'need_volunteer_for_delivery': 'वितरणासाठी स्वयंसेवकाची आवश्यकता आहे',
      'volunteer_note': 'टीप: जेव्हा तुमचे दान एखाद्या प्राप्तकर्त्याने स्वीकारले जाते, तेव्हा त्यांना वितरणासाठी स्वयंसेवकाची विनंती करता येईल.',
      'donation_posted_successfully': 'दान यशस्वीरित्या पोस्ट केले!',
      'failed_to_post_donation': 'दान पोस्ट करण्यात अयशस्वी. कृपया पुन्हा प्रयास करा.',
      'authentication_error_refresh': 'प्रमाणीकरण त्रुटी: कृपया अपने क्रेडेंशियल्स को रीफ्रेश करने के लिए साइन आउट करें और फिर से साइन इन करें।',
      'authentication_error': 'प्रमाणीकरण त्रुटी',
      'auth_error_details': 'आपकी दाता प्रोफ़ाइल सत्यापित नहीं की जा सकी। ऐसा हो सकता है:\n\n1. आपने हाल ही में पंजीकरण किया है और आपकी प्रोफ़ाइल पूरी तरह से सिंक नहीं हुई है\n2. आपका प्रमाणीकरण टोकन समाप्त हो गया है\n\nकृपया अपने क्रेडेंशियल्स को रीफ्रेश करने के लिए साइन आउट करें और फिर से साइन इन करें।',
      'ok': 'ठीक है',
      'sign_out_now': 'अभी साइन आउट करें',
      
      // Charity donation screen
      'donate': 'दान करा',
      'select_amount': 'रक्कम निवडा',
      'custom_amount': 'इतर रक्कम',
      'payment_method': 'पेमेंट पद्धत',
      'upi': 'यूपीआई',
      'card': 'क्रेडिट/डेबिट कार्ड',
      'net_banking': 'नेट बँकिंग',
      'enter_valid_amount': 'कृपया वैध रक्कम प्रविष्ट करा',
      'amount_must_be_greater': 'रक्कम 10 पेक्षा जास्त असावी',
      'select_payment_method': 'कृपया पेमेंट पद्धत निवडा',
      'donate_caps': 'दान करा',
      
      // Donor history translations
      'no_donations_found': 'कोणतेही दान सापडले नाही',
      'create_donations_to_see': 'येथे पाहण्यासाठी दान करा',
      'create_donation': 'दान करा',
      'no_donation_history_found': 'कोई दान इतिहास नहीं मिला। कृपया बाद में फिर से प्रयास करें।',
      'sign_in_to_view_donations': 'अपने दान इतिहास को देखने के लिए कृपया साइन इन करें।',
      'all': 'सभी',
      
      // View donations screen
      'available_donations': 'उपलब्ध दाने',
      'filter_donations': 'दान फिल्टर करा',
      'food_type': 'अन्नाचा प्रकार',
      'sort_by': 'याद्वारे क्रमवा',
      'sort_by_expiry': 'कालबाह्य तारीख',
      'sort_by_distance': 'अंतर',
      'sort_by_quantity': 'प्रमाण',
      'maximum_distance': 'कमाल अंतर',
      'km': 'किमी',
      'show_needs_volunteer': 'स्वयंसेवक मदतीची आवश्यकता असलेली दाने दाखवा',
      'reset': 'रीसेट करा',
      'apply_filters': 'फिल्टर लागू करा',
      'search_food': 'अन्न शोधा...',
      'filter': 'फिल्टर',
      'needs_volunteer': 'स्वयंसेवकाची गरज आहे',
      'no_available_donations': 'कोणतीही उपलब्ध दाने सापडली नाहीत',
      'no_results_for': 'यासाठी कोणतेही परिणाम सापडले नाहीत',
      'check_back_later': 'नवीन दानांसाठी नंतर पुन्हा तपासा',
      'try_changing_filters': 'अधिक दाने पाहण्यासाठी तुमचे फिल्टर बदलण्याचा प्रयत्न करा',
      'clear_filters': 'फिल्टर साफ करा',
      'profile_not_found_recipient': 'तुमचे प्रोफाइल सापडले नाही. दाने पाहण्यासाठी तुम्ही प्राप्तकर्ता म्हणून नोंदणीकृत असल्याची खात्री करा.',
      'unable_to_load_donations': 'या वेळी दाने लोड करण्यास अक्षम. कृपया नंतर पुन्हा प्रयत्न करा.',
      'retry': 'पुन्हा प्रयत्न करा',
      'go_to_profile': 'प्रोफाइलवर जा',
      'no_image_available': 'कोणतीही प्रतिमा उपलब्ध नाही',
      'expiring_soon': 'लवकरच कालबाह्य होत आहे',
      'quantity': 'प्रमाण',
      'servings': 'वाटप',
      'tap_to_read_more': 'अधिक वाचण्यासाठी टॅप करा',
      'donor': 'दाता',
      'call_donor': 'दात्यास कॉल करा',
      'get_directions': 'दिशा मिळवा',
      'expires': 'कालबाह्य होते',
      'view_details': 'तपशील पहा',
      'unknown_location': 'अज्ञात स्थान',
      'anonymous': 'अनामित',
      'error': 'त्रुटी',
      'refresh': 'रिफ्रेश करा',
      
      // Recipient history screen (Hindi)
      'recipient_history': 'प्राप्तकर्ता इतिहास',
      'my_recipient_history': 'मेरा प्राप्तकर्ता इतिहास',
      'donations_accepted': 'स्वीकृत दान',
      'no_accepted_donations': 'कोई स्वीकृत दान नहीं',
      'accept_a_donation': 'एक दान स्वीकारें',
      'filter_history': 'इतिहास फ़िल्टर करें',
      'meals_received': 'प्राप्त भोजन',
      'request_volunteer': 'स्वयंसेवक का अनुरोध करें',
      'volunteer_requested': 'स्वयंसेवक का अनुरोध किया गया',
      'cancel_volunteer_request': 'स्वयंसेवक अनुरोध रद्द करें',
      'pickup_yourself': 'स्वयं पिकअप करें',
      'volunteer_confirmed': 'स्वयंसेवक की पुष्टि की गई',
      'volunteer_name': 'स्वयंसेवक का नाम',
      'volunteer_phone': 'स्वयंसेवक का फोन',
      'confirm_receipt': 'रसीद की पुष्टि करें',
      'confirm_receipt_question': 'क्या आप पुष्टि करना चाहते हैं कि आपने दान प्राप्त कर लिया है?',
      'yes_received': 'हां, प्राप्त किया',
      'not_yet': 'अभी नहीं',
      'receipt_confirmed': 'रसीद की पुष्टि की गई',
      'add_review': 'समीक्षा जोड़ें',
      'view_receipt_details': 'रसीद विवरण देखें',
      
      // Recipient history screen (old translations - keep for compatibility)
      'filter_donation_history': 'दान इतिहास फ़िल्टर करें',
      'time_period': 'समय अवधि',
      'today': 'आज',
      'yesterday': 'कल',
      'days_ago': 'दिन पहले',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'time': 'समय',
      'type': 'प्रकार',
      'accept_donations_to_see': 'यहां देखने के लिए दान स्वीकार करें',
      'browse_donations': 'दान ब्राउज़ करें',
      'no_donations_match_criteria': 'कोई दान आपके मानदंडों से मेल नहीं खाता',
      'try_adjusting_filters': 'अधिक दान देखने के लिए अपने फिल्टर समायोजित करने का प्रयास करें',
      'clear_all_filters': 'सभी फिल्टर साफ़ करें',
      'update_location': 'स्थान अपडेट करें',
      'no_donations_found': 'कोई दान इतिहास नहीं मिला',
      'create_donations_to_see': 'यहां देखने के लिए दान बनाएं',
      'create_donation': 'दान बनाएं',
      'all': 'सभी',
      'active': 'सक्रिय',
      'accepted': 'स्वीकृत',
      'expired': 'समाप्त',
      'search_food_by_name': 'भोजन का नाम खोजें...',
      'no_filtered_donations_found': 'कोई {0} दान नहीं मिला',
      'no_search_results_found': '"{0}" के लिए कोई परिणाम नहीं मिला',
      'unknown': 'अज्ञात',
      'created': 'बनाया गया',
      'expires': 'समाप्त होता है',
      'tap_to_read_more': 'अधिक पढ़ने के लिए टैप करें',
      'close': 'बंद करें',
      'accepted_by': 'स्वीकारकर्ता',
      'accepted_on': 'स्वीकृति तिथि',
      'expired_on': 'समाप्ति तिथि',
      'signed_out': 'साइन आउट किया गया',
      'sign_out_confirmation': 'क्या आप साइन आउट करना चाहते हैं?',
      'sign_out': 'साइन आउट',
      'yes': 'हां',
      'no': 'नहीं',
      'ok': 'ठीक है',
      'sign_out_now': 'अभी साइन आउट करें',
      
      // Recipient history screen
      'recipient_history': 'प्राप्तकर्ता इतिहास',
      'my_recipient_history': 'माझा प्राप्तकर्ता इतिहास',
      'donations_accepted': 'स्वीकारलेली दाने',
      'no_accepted_donations': 'कोणतीही स्वीकारलेली दाने नाहीत',
      'accept_a_donation': 'दान स्वीकारा',
      'filter_history': 'इतिहास फिल्टर करा',
      'meals_received': 'प्राप्त केलेली जेवणे',
      'unknown_location': 'अज्ञात स्थान',
      'anonymous': 'अनामित',
      'get_directions': 'दिशा मिळवा',
      'request_volunteer': 'स्वयंसेवकाची विनंती करा',
      'volunteer_requested': 'स्वयंसेवकाची विनंती केली',
      'cancel_volunteer_request': 'स्वयंसेवक विनंती रद्द करा',
      'pickup_yourself': 'स्वतः पिकअप करें',
      'volunteer_confirmed': 'स्वयंसेवक निश्चित केला',
      'volunteer_name': 'स्वयंसेवक का नाम',
      'volunteer_phone': 'स्वयंसेवक का फोन',
      'confirm_receipt': 'प्राप्ती निश्चित करा',
      'confirm_receipt_question': 'तुम्ही दान प्राप्त केल्याची पुष्टी करू इच्छिता?',
      'yes_received': 'होय, प्राप्त केले',
      'not_yet': 'अजून नाही',
      'receipt_confirmed': 'प्राप्ती निश्चित केली',
      'add_review': 'परीक्षण जोडा',
      'view_receipt_details': 'प्राप्ती तपशील पहा',
      'distance': 'दूरी',
      'submit': 'सबमिट करा',
      
      // Donation detail screen
      'donation_details': 'दान तपशील',
      'unknown_food': 'अज्ञात अन्न',
      'no_description_available': 'कोणतेही वर्णन उपलब्ध नाही',
      'unknown': 'अज्ञात',
      'servings': 'वाटप',
      'anonymous_donor': 'अनामित दाता',
      'donor_information': 'दात्याची माहिती',
      'donor': 'दाता',
      'location': 'स्थान',
      'food_description': 'अन्न वर्णन',
      'expires': 'कालबाह्य होते',
      'exact_expiry': 'नेमकी कालबाह्यता',
      'delivery_options': 'वितरण पर्याय',
      'need_volunteer_assistance': 'स्वयंसेवक मदत हवी आहे?',
      'yes_request_volunteer': 'होय, वितरणासाठी स्वयंसेवक मदत विनंती करा',
      'no_pickup_myself': 'नाही, मी हे दान स्वतः घेऊन जाईन',
      'changed_from_original': 'तुम्ही हे दात्याच्या मूळ सेटिंगमधून बदलले आहे',
      'using_donor_preference': 'दात्याचा पसंतीचा वितरण पर्याय वापरत आहे',
      'accept_donation': 'हे दान स्वीकारा',
      'donation_accepted_with_volunteer': 'दान यशस्वीरीत्या स्वीकारले. एक स्वयंसेवक वितरणासाठी मदत करेल.',
      'donation_accepted_self_pickup': 'दान यशस्वीरीत्या स्वीकारले. तुम्हाला हे स्वतः संकलित करावे लागेल.',
    },
  };

  // Method to get translation for a key
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  // Singleton instance to keep track of the current language
  static final AppLocalizationsService localizationsService = AppLocalizationsService();
}

// A class to manage the app language state
class AppLocalizationsService extends ChangeNotifier {
  AppLanguage _currentLanguage = AppLanguage.english;
  
  // Local storage key for saving language preference
  static const String _languagePreferenceKey = 'app_language';

  AppLanguage get currentLanguage => _currentLanguage;
  
  // Get the current locale
  Locale get currentLocale => Locale(languageCodes[_currentLanguage]!);

  // Load the saved language preference
  Future<void> loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_languagePreferenceKey);
    
    if (savedCode != null) {
      _currentLanguage = getLanguageFromCode(savedCode);
      notifyListeners();
    }
  }

  // Change the app language
  Future<void> changeLanguage(AppLanguage language) async {
    if (_currentLanguage != language) {
      _currentLanguage = language;
      
      // Save the language preference
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_languagePreferenceKey, languageCodes[language]!);
      
      notifyListeners();
    }
  }
}

// LocalizationsDelegate implementation
class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
} 